name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Type check
        run: npm run check

      - name: Build
        run: npx run build:web

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build-${{ matrix.node-version }}
          path: dist/
          if-no-files-found: error
